spring:
  application:
    name: gestao_vagas
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

security:
  token:
    secret:
      candidate: 'JAVAGAS_@123#CANDIDATE'
      company: 'JAVAGAS_@123'

management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: 'health,metrics,prometheus'
    enabled-by-default: false